export const FETCH_PAYMENT_GRAPH_REQUEST = "FETCH_PAYMENT_GRAPH_REQUEST";
export const FETCH_PAYMENT_GRAPH_SUCCESS = "FETCH_PAYMENT_GRAPH_SUCCESS";
export const FETCH_PAYMENT_GRAPH_FAILURE = "FETCH_PAYMENT_GRAPH_FAILURE";